name: Sync To Gitee
on:
  push:
    branches:
      - gh-pages
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/yingliyu'
          dst: 'gitee/yingliyu-code'
          dst_key: ${{ secrets.ACCESS_TOKEN }}
          # dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "fish-design"
          force_update: true
          debug: true
          
      - name: Build Gitee Pages
          uses: yanglbme/gitee-pages-action@main
          with:
            # 注意替换为你的 Gitee 用户名
            gitee-username: yingliyu-code
            # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
            gitee-password: ${{ secrets.GITEE_PASSWORD }}
            # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
            gitee-repo: yingliyu-code/fish-design
            # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
            branch: gh-pages


name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
      - gh-pages
      - feature
      - 2.x-stable
      - 3.x-stable
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'yingliyu/fish-design'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:yingliyu/fish-design.git'
          destination-repo: 'git@gitee.com:yingliyu-code/fish-design.git'
