name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
      - gh-pages
  create:

jobs:
  mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'yingliyu/fish-design'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag')
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN_GITEE }}
        with:
          source-repo: 'git@github.com:yingliyu/fish-design.git'
          destination-repo: 'git@gitee.com:yingliyu-code/fish-design.git'
